#!/bin/zsh

BUILD_DIR=build
MAIN_EXE=mezze

LOCAL_C_COMPILER_PATH=gcc
LOCAL_CXX_COMPILER_PATH=g++

LOCAL_CXX_COMPILER_FLAGS="-std=c++23 -O3 -Ofast -march=native -mtune=native"

mkdir ${BUILD_DIR}
cd ${BUILD_DIR}

cmake -DCMAKE_OSX_SYSROOT="" \
      -DCMAKE_C_COMPILER=${LOCAL_C_COMPILER_PATH} \
      -DCMAKE_CXX_COMPILER=${LOCAL_CXX_COMPILER_PATH} \
      -DCMAKE_CXX_FLAGS=${LOCAL_CXX_COMPILER_FLAGS} \
      -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..

make

./${MAIN_EXE}
